spring.application.name=notification
server.port=8088

spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.default.group=notification
spring.cloud.stream.default.consumer.auto-offset-reset=earliest

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=0.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
