spring.application.name=order
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=app
spring.datasource.password=app
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.default.group=order
spring.cloud.stream.default.consumer.auto-offset-reset=earliest

services.inventory.url=http://localhost:8083
services.payment.url=http://localhost:8086

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=0.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
