spring.application.name=waitingroom
server.port=8089

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=0.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
