spring.application.name=auth
server.port=8081

# === PostgreSQL riêng của Auth (database-per-service) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=app
spring.datasource.password=app
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# === Actuator / metrics ===
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=0.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
